language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

script:
  - python USSSALoader.py
  - python fi_loader.py
  - python genderPredictor.py

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py
  - pyflakes *.py

matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: pypy
